// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.9.0
// source: rag.proto

package rag_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	ArticleId     string                 `protobuf:"bytes,2,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RagRequest) Reset() {
	*x = RagRequest{}
	mi := &file_rag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RagRequest) ProtoMessage() {}

func (x *RagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RagRequest.ProtoReflect.Descriptor instead.
func (*RagRequest) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{0}
}

func (x *RagRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RagRequest) GetArticleId() string {
	if x != nil {
		return x.ArticleId
	}
	return ""
}

func (x *RagRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type RagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RagResponse) Reset() {
	*x = RagResponse{}
	mi := &file_rag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RagResponse) ProtoMessage() {}

func (x *RagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RagResponse.ProtoReflect.Descriptor instead.
func (*RagResponse) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{1}
}

func (x *RagResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type RagSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RagSearchRequest) Reset() {
	*x = RagSearchRequest{}
	mi := &file_rag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RagSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RagSearchRequest) ProtoMessage() {}

func (x *RagSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RagSearchRequest.ProtoReflect.Descriptor instead.
func (*RagSearchRequest) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{2}
}

func (x *RagSearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type RagSearchResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Items         []*RagSearchResponse_RagItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RagSearchResponse) Reset() {
	*x = RagSearchResponse{}
	mi := &file_rag_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RagSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RagSearchResponse) ProtoMessage() {}

func (x *RagSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RagSearchResponse.ProtoReflect.Descriptor instead.
func (*RagSearchResponse) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{3}
}

func (x *RagSearchResponse) GetItems() []*RagSearchResponse_RagItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type RagQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      string                 `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RagQuestionRequest) Reset() {
	*x = RagQuestionRequest{}
	mi := &file_rag_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RagQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RagQuestionRequest) ProtoMessage() {}

func (x *RagQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RagQuestionRequest.ProtoReflect.Descriptor instead.
func (*RagQuestionRequest) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{4}
}

func (x *RagQuestionRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

type RagQuestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Answer        string                 `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RagQuestionResponse) Reset() {
	*x = RagQuestionResponse{}
	mi := &file_rag_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RagQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RagQuestionResponse) ProtoMessage() {}

func (x *RagQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RagQuestionResponse.ProtoReflect.Descriptor instead.
func (*RagQuestionResponse) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{5}
}

func (x *RagQuestionResponse) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

type RagSearchResponse_RagItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleId     string                 `protobuf:"bytes,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RagSearchResponse_RagItem) Reset() {
	*x = RagSearchResponse_RagItem{}
	mi := &file_rag_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RagSearchResponse_RagItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RagSearchResponse_RagItem) ProtoMessage() {}

func (x *RagSearchResponse_RagItem) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RagSearchResponse_RagItem.ProtoReflect.Descriptor instead.
func (*RagSearchResponse_RagItem) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{3, 0}
}

func (x *RagSearchResponse_RagItem) GetArticleId() string {
	if x != nil {
		return x.ArticleId
	}
	return ""
}

func (x *RagSearchResponse_RagItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

var File_rag_proto protoreflect.FileDescriptor

const file_rag_proto_rawDesc = "" +
	"\n" +
	"\trag.proto\x12\x03rag\"[\n" +
	"\n" +
	"RagRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x1d\n" +
	"\n" +
	"article_id\x18\x02 \x01(\tR\tarticleId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"\x1d\n" +
	"\vRagResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"(\n" +
	"\x10RagSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"\x89\x01\n" +
	"\x11RagSearchResponse\x124\n" +
	"\x05items\x18\x01 \x03(\v2\x1e.rag.RagSearchResponse.RagItemR\x05items\x1a>\n" +
	"\aRagItem\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\tR\tarticleId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\"0\n" +
	"\x12RagQuestionRequest\x12\x1a\n" +
	"\bquestion\x18\x01 \x01(\tR\bquestion\"-\n" +
	"\x13RagQuestionResponse\x12\x16\n" +
	"\x06answer\x18\x01 \x01(\tR\x06answer2\xb8\x01\n" +
	"\n" +
	"RagService\x12-\n" +
	"\x06AddRag\x12\x0f.rag.RagRequest\x1a\x10.rag.RagResponse\"\x00\x12<\n" +
	"\tSearchRag\x12\x15.rag.RagSearchRequest\x1a\x16.rag.RagSearchResponse\"\x00\x12=\n" +
	"\x06AskRag\x12\x17.rag.RagQuestionRequest\x1a\x18.rag.RagQuestionResponse\"\x00B\fZ\n" +
	"./rag_grpcb\x06proto3"

var (
	file_rag_proto_rawDescOnce sync.Once
	file_rag_proto_rawDescData []byte
)

func file_rag_proto_rawDescGZIP() []byte {
	file_rag_proto_rawDescOnce.Do(func() {
		file_rag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rag_proto_rawDesc), len(file_rag_proto_rawDesc)))
	})
	return file_rag_proto_rawDescData
}

var file_rag_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_rag_proto_goTypes = []any{
	(*RagRequest)(nil),                // 0: rag.RagRequest
	(*RagResponse)(nil),               // 1: rag.RagResponse
	(*RagSearchRequest)(nil),          // 2: rag.RagSearchRequest
	(*RagSearchResponse)(nil),         // 3: rag.RagSearchResponse
	(*RagQuestionRequest)(nil),        // 4: rag.RagQuestionRequest
	(*RagQuestionResponse)(nil),       // 5: rag.RagQuestionResponse
	(*RagSearchResponse_RagItem)(nil), // 6: rag.RagSearchResponse.RagItem
}
var file_rag_proto_depIdxs = []int32{
	6, // 0: rag.RagSearchResponse.items:type_name -> rag.RagSearchResponse.RagItem
	0, // 1: rag.RagService.AddRag:input_type -> rag.RagRequest
	2, // 2: rag.RagService.SearchRag:input_type -> rag.RagSearchRequest
	4, // 3: rag.RagService.AskRag:input_type -> rag.RagQuestionRequest
	1, // 4: rag.RagService.AddRag:output_type -> rag.RagResponse
	3, // 5: rag.RagService.SearchRag:output_type -> rag.RagSearchResponse
	5, // 6: rag.RagService.AskRag:output_type -> rag.RagQuestionResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rag_proto_init() }
func file_rag_proto_init() {
	if File_rag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rag_proto_rawDesc), len(file_rag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rag_proto_goTypes,
		DependencyIndexes: file_rag_proto_depIdxs,
		MessageInfos:      file_rag_proto_msgTypes,
	}.Build()
	File_rag_proto = out.File
	file_rag_proto_goTypes = nil
	file_rag_proto_depIdxs = nil
}
