// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.9.0
// source: rag.proto

package rag_grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RagService_AddRag_FullMethodName    = "/rag.RagService/AddRag"
	RagService_SearchRag_FullMethodName = "/rag.RagService/SearchRag"
	RagService_AskRag_FullMethodName    = "/rag.RagService/AskRag"
)

// RagServiceClient is the client API for RagService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RagServiceClient interface {
	AddRag(ctx context.Context, in *RagRequest, opts ...grpc.CallOption) (*RagResponse, error)
	SearchRag(ctx context.Context, in *RagSearchRequest, opts ...grpc.CallOption) (*RagSearchResponse, error)
	AskRag(ctx context.Context, in *RagQuestionRequest, opts ...grpc.CallOption) (*RagQuestionResponse, error)
}

type ragServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRagServiceClient(cc grpc.ClientConnInterface) RagServiceClient {
	return &ragServiceClient{cc}
}

func (c *ragServiceClient) AddRag(ctx context.Context, in *RagRequest, opts ...grpc.CallOption) (*RagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RagResponse)
	err := c.cc.Invoke(ctx, RagService_AddRag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragServiceClient) SearchRag(ctx context.Context, in *RagSearchRequest, opts ...grpc.CallOption) (*RagSearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RagSearchResponse)
	err := c.cc.Invoke(ctx, RagService_SearchRag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragServiceClient) AskRag(ctx context.Context, in *RagQuestionRequest, opts ...grpc.CallOption) (*RagQuestionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RagQuestionResponse)
	err := c.cc.Invoke(ctx, RagService_AskRag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RagServiceServer is the server API for RagService service.
// All implementations must embed UnimplementedRagServiceServer
// for forward compatibility.
type RagServiceServer interface {
	AddRag(context.Context, *RagRequest) (*RagResponse, error)
	SearchRag(context.Context, *RagSearchRequest) (*RagSearchResponse, error)
	AskRag(context.Context, *RagQuestionRequest) (*RagQuestionResponse, error)
	mustEmbedUnimplementedRagServiceServer()
}

// UnimplementedRagServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRagServiceServer struct{}

func (UnimplementedRagServiceServer) AddRag(context.Context, *RagRequest) (*RagResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddRag not implemented")
}
func (UnimplementedRagServiceServer) SearchRag(context.Context, *RagSearchRequest) (*RagSearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchRag not implemented")
}
func (UnimplementedRagServiceServer) AskRag(context.Context, *RagQuestionRequest) (*RagQuestionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AskRag not implemented")
}
func (UnimplementedRagServiceServer) mustEmbedUnimplementedRagServiceServer() {}
func (UnimplementedRagServiceServer) testEmbeddedByValue()                    {}

// UnsafeRagServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RagServiceServer will
// result in compilation errors.
type UnsafeRagServiceServer interface {
	mustEmbedUnimplementedRagServiceServer()
}

func RegisterRagServiceServer(s grpc.ServiceRegistrar, srv RagServiceServer) {
	// If the following call panics, it indicates UnimplementedRagServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RagService_ServiceDesc, srv)
}

func _RagService_AddRag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServiceServer).AddRag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagService_AddRag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServiceServer).AddRag(ctx, req.(*RagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagService_SearchRag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RagSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServiceServer).SearchRag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagService_SearchRag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServiceServer).SearchRag(ctx, req.(*RagSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagService_AskRag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RagQuestionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServiceServer).AskRag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagService_AskRag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServiceServer).AskRag(ctx, req.(*RagQuestionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RagService_ServiceDesc is the grpc.ServiceDesc for RagService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RagService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rag.RagService",
	HandlerType: (*RagServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddRag",
			Handler:    _RagService_AddRag_Handler,
		},
		{
			MethodName: "SearchRag",
			Handler:    _RagService_SearchRag_Handler,
		},
		{
			MethodName: "AskRag",
			Handler:    _RagService_AskRag_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rag.proto",
}
