# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rag.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'rag.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\trag.proto\x12\x03rag\"@\n\nRagRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x12\n\narticle_id\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\"\x19\n\x0bRagResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\"!\n\x10RagSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\"p\n\x11RagSearchResponse\x12-\n\x05items\x18\x01 \x03(\x0b\x32\x1e.rag.RagSearchResponse.RagItem\x1a,\n\x07RagItem\x12\x12\n\narticle_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t2y\n\nRagService\x12-\n\x06\x41\x64\x64Rag\x12\x0f.rag.RagRequest\x1a\x10.rag.RagResponse\"\x00\x12<\n\tSearchRag\x12\x15.rag.RagSearchRequest\x1a\x16.rag.RagSearchResponse\"\x00\x42\x0cZ\n./rag_grpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rag_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\n./rag_grpc'
  _globals['_RAGREQUEST']._serialized_start=18
  _globals['_RAGREQUEST']._serialized_end=82
  _globals['_RAGRESPONSE']._serialized_start=84
  _globals['_RAGRESPONSE']._serialized_end=109
  _globals['_RAGSEARCHREQUEST']._serialized_start=111
  _globals['_RAGSEARCHREQUEST']._serialized_end=144
  _globals['_RAGSEARCHRESPONSE']._serialized_start=146
  _globals['_RAGSEARCHRESPONSE']._serialized_end=258
  _globals['_RAGSEARCHRESPONSE_RAGITEM']._serialized_start=214
  _globals['_RAGSEARCHRESPONSE_RAGITEM']._serialized_end=258
  _globals['_RAGSERVICE']._serialized_start=260
  _globals['_RAGSERVICE']._serialized_end=381
# @@protoc_insertion_point(module_scope)
